id: IEC8A8BA7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:06:49+00:00'
last_modified: '2022-06-10T06:30:27.599287+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9042
  title: དཔལ་གསང་བའི་སྙིང་པོའི་འགྲེལ་པ་ཕྱོགས་བཅུའི་མུན་སེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8AE5:
      image_group_id: I1KG9074
      title: Volume 1 of dpal gsang ba'i snying po'i 'grel pa phyogs bcu'i mun sel/
      total_pages: 658
      order: 1
      base_file: 8AE5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
